import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
const api=async(path:string,opts?:RequestInit)=>{const r=await fetch('/api/v1'+path,{headers:{'Content-Type':'application/json',...(opts?.headers||{})},...opts});const d=await r.json();if(!r.ok)throw Error(d.message||'请求失败');return d};
type Tour=any;
function App(){const[tour,setTour]=useState<Tour|null>(null);const[data,setData]=useState<any>();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[perf,setPerf]=useState<any>();const[draft,setDraft]=useState<any>({playId:'moon',assignments:{},timeline:[],endings:[0,0,0]});const[pending,setPending]=useState<any>(null);const[errors,setErrors]=useState<string[]>([]);
 useEffect(()=>{api('/tours').then(d=>{const id=localStorage.getItem('tour');if(id)api('/tours/'+id).then(x=>{setTour(x.tour);setData(x)}).catch(()=>{localStorage.removeItem('tour');setMsg('存档读取失败，请开始新的巡演。')})}).catch(()=>setMsg('无法连接巡演服务，请确认 API 已启动后重试。'))},[]);
 const act=async(fn:()=>Promise<any>)=>{setBusy(true);setMsg('');try{const d=await fn();if(d.tour){setTour(d.tour);setData({...d,...data})}if(d.performance)setPerf(d.performance);if(d.ending)setMsg(`终局：${d.ending}（平均 ${d.average} 分）`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const create=()=>act(async()=>{const created=await api('/tours',{method:'POST',body:JSON.stringify({name:'纸月剧团'})});localStorage.setItem('tour',created.tour.id);const d=await api('/tours/'+created.tour.id);setData(d);return d});
 useEffect(()=>{if(tour&&(tour.status==='PREPARING'||tour.status==='READY'))api('/tours/'+tour.id+'/production').then(d=>setDraft(d.draft))},[tour?.id,tour?.status]);
 if(!tour)return <main className="landing"><div className="curtain"><span>木偶剧团</span><h1>巡演</h1><p>把一段传说，交给下一座小镇。</p>{msg&&<div className="notice">{msg}</div>}<button onClick={create}>开始一场新的巡演</button></div></main>;
 const town=data?.town;const nextId=tour.townIds[tour.stopIndex+1];const next=data?.towns?.find((x:any)=>x.id===nextId);
 const travel=()=>next&&act(async()=>{const d=await api('/tours/'+tour.id+'/travel',{method:'POST',body:JSON.stringify({townId:next.id})});return d});
 const investigate=(kind:string)=>act(async()=>api('/tours/'+tour.id+'/investigations',{method:'POST',body:JSON.stringify({kind})}));
 const choosePlay=(id:string)=>setDraft((x:any)=>({...x,playId:id}));
 const findAction=(id:string)=>data?.actions?.find((a:any)=>a.id===id);
 const findActor=(id:string)=>tour.actors.find((a:any)=>a.id===id);
 // 时间轴看板：cell[act][beat] 存放落在该拍的条目列表
 const board=()=>{const cells:any[][][]=Array.from({length:3},()=>Array.from({length:4},()=>[]));for(const[e,i]of(draft.timeline||[]).map((x:any,j:number)=>[x,j])){const a=findAction(e.actionId);const dur=a?.duration||1;for(let b=e.slot;b<Math.min(4,e.slot+dur);b++)cells[e.act]?.[b]?.push({e,i,a,dur})}return cells};
 const occupied=(act:number,beat:number,ignore?:number)=>{const ids=new Set<string>();(draft.timeline||[]).forEach((e:any,i:number)=>{if(i===ignore)return;const dur=findAction(e.actionId)?.duration||1;if(e.act===act&&beat>=e.slot&&beat<e.slot+dur)e.actorIds.forEach((id:string)=>ids.add(id))});return ids};
 const togglePendingActor=(id:string)=>setPending((p:any)=>p?({...p,actorIds:p.actorIds.includes(id)?p.actorIds.filter((x:string)=>x!==id):[...p.actorIds,id]}):p);
 const rangeBusy=(act:number,start:number,len:number,actorIds:string[],ignore?:number)=>{for(let beat=start;beat<Math.min(4,start+len);beat++){if(Array.from(occupied(act,beat,ignore)).some((id:string)=>actorIds.includes(id)))return beat}return -1};
 const placePending=()=>{if(!pending)return;const a=findAction(pending.actionId);const dur=a?.duration||1;const minActors=a?.minActors??1;if(pending.actorIds.length<minActors){setErrors([`「${a.name}」需要至少 ${minActors} 名演员协作`]);return}if(pending.slot+dur>4){setErrors(['动作时长越过本幕结尾，请选择更早的拍位']);return}const clashBeat=rangeBusy(pending.act,pending.slot,dur,pending.actorIds);if(clashBeat>=0){setErrors([`所选演员在第${clashBeat+1}拍已有动作（长动作会连续占位）`]);return}setDraft((x:any)=>({...x,timeline:[...x.timeline,{actionId:pending.actionId,actorIds:pending.actorIds,act:pending.act,slot:pending.slot}]}));setPending(null);setErrors([])};
 const removeEntry=(i:number)=>setDraft((x:any)=>({...x,timeline:x.timeline.filter((_:any,j:number)=>j!==i)}));
 // 一键套用合法基线：每幕 slot0 全员入场、中段走位、slot3 全员退场
 const applyTemplate=()=>{const ids=tour.actors.map((a:any)=>a.id);const tl:any[]=[];for(let act=0;act<3;act++){tl.push({actionId:'enter',actorIds:ids,act,slot:0});tour.actors.forEach((a:any,k:number)=>tl.push({actionId:'bow',actorIds:[a.id],act,slot:1+(k%3)}));tl.push({actionId:'exit',actorIds:ids,act,slot:3})}setDraft((x:any)=>({...x,timeline:tl}));setErrors([])};
 const saveProduction=()=>act(async()=>{const v=await api('/tours/'+tour.id+'/production/validate',{method:'POST',body:JSON.stringify(draft)});setErrors(v.valid?[]:v.errors);if(!v.valid)throw Error(v.errors.join('；'));return api('/tours/'+tour.id+'/production',{method:'PUT',body:JSON.stringify(draft)})});
 const perform=()=>act(async()=>api('/tours/'+tour.id+'/performances',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(draft)}));const rest=()=>act(async()=>api('/tours/'+tour.id+'/rest',{method:'POST'}));const finale=()=>act(async()=>api('/tours/'+tour.id+'/finale',{method:'POST'}));
 return <div className="app"><header><div className="brand">木偶剧团巡演</div><div className="stats"><b>第 {tour.stopIndex+1} 站</b><span>资金 {tour.funds}</span><span>声望 {tour.reputation}</span><span>灵感 {tour.inspiration}</span></div></header><main className="shell"><section className="hero"><div><small>{town?.region||'巡演路上'}</small><h1>{tour.status==='COMPLETED'?'巡演落幕':town?.name||'下一站'}</h1><p>{tour.status==='COMPLETED'?msg||'每一次提线，都会留下回声。':town?`${town.legend} · ${town.audience}`:'选择路线，去遇见新的传说。'}</p></div><div className="status">{tour.status.replaceAll('_',' ')}</div></section>{msg&&<div className="notice">{msg}</div>}
 {tour.status==='ROUTE_SELECTION'&&<section className="panel"><h2>选择下一站</h2><div className="route"><div className="town current"><strong>{town?.name||'起点'}</strong><small>当前剧场</small></div><div className="path">→</div><button className="town choice" onClick={travel} disabled={!next||busy}><strong>{next?.name||'路线已结束'}</strong><small>{next?`旅费 ${Math.max(12,Math.round(next.capacity/8))} · ${next.legend}`:'准备终场'}</small></button></div><button className="secondary" onClick={rest}>让全员休息，恢复 25 体力</button>{tour.stopIndex>=tour.townIds.length-1&&<button onClick={finale}>进入终局</button>}</section>}
 {tour.status==='INVESTIGATING'&&<section className="panel"><h2>在 {town.name} 了解传说</h2><p className="muted">调查会揭示结尾线索，排练则让动作更稳。</p><div className="choices"><button onClick={()=>investigate('market')}>逛市集<small>寻找观众口味</small></button><button onClick={()=>investigate('tavern')}>听酒馆故事<small>了解传说禁忌</small></button><button onClick={()=>investigate('shrine')}>拜访神龛<small>确认象征物</small></button><button onClick={()=>investigate('rehearse')}>后台排练<small>不揭示线索</small></button></div></section>}
 {(tour.status==='PREPARING'||tour.status==='READY')&&<section className="grid"><div className="panel"><h2>选一出戏</h2><div className="play-list">{(data?.plays||[]).map((p:any)=><button className={draft.playId===p.id?'selected':''} key={p.id} onClick={()=>choosePlay(p.id)}><b>{p.name}</b><small>{p.blurb}</small><em>{p.tags.join(' · ')}</em></button>)}</div></div><div className="panel"><h2>编排木偶动作</h2><p className="muted">每幕 4 拍。2 拍动作会连续占位，同一演员在占位区间内不得重叠；每幕须先入场、后退场；联合托举至少 2 人。</p>
{errors.length>0&&<div className="notice validation">{errors.map((x,i)=><div key={i}>· {x}</div>)}</div>}
{pending?<div className="placer"><h3>放置「{findAction(pending.actionId)?.name}」<small>{findAction(pending.actionId)?.duration} 拍 · {findAction(pending.actionId)?.stamina} 体力{(findAction(pending.actionId)?.minActors??1)>1?` · 至少 ${findAction(pending.actionId).minActors} 人协作`:''}</small></h3>
<label>幕次<select value={pending.act} onChange={ev=>setPending({...pending,act:Number(ev.target.value)})}>{[0,1,2].map(a=><option key={a} value={a}>第 {a+1} 幕</option>)}</select></label>
<label>起始拍<select value={pending.slot} onChange={ev=>setPending({...pending,slot:Number(ev.target.value)})}>{[0,1,2,3].map(s=><option key={s} value={s} disabled={s+(findAction(pending.actionId)?.duration||1)>4}>第 {s+1} 拍{s+(findAction(pending.actionId)?.duration||1)>4?'（越界）':''}</option>)}</select></label>
<div className="pick-actors">参演{tour.actors.map((a:any)=>{const beat=rangeBusy(pending.act,pending.slot,findAction(pending.actionId)?.duration||1,[a.id]);return <button key={a.id} type="button" className={pending.actorIds.includes(a.id)?'selected':beat>=0?'busy':''} disabled={beat>=0} onClick={()=>togglePendingActor(a.id)}>{a.name}{beat>=0?` · 第${beat+1}拍占用`:''}</button>})}</div>
<div className="placer-actions"><button onClick={placePending}>放入时间轴</button><button className="secondary" onClick={()=>{setPending(null);setErrors([])}}>取消</button></div></div>
:<><div className="actions">{(data?.actions||[]).map((a:any)=><button key={a.id} onClick={()=>setPending({actionId:a.id,actorIds:[tour.actors[0].id],act:0,slot:0})}>{a.name}<small>{a.duration} 拍 · {a.stamina} 体力{a.minActors?` · 协作≥${a.minActors}`:''}</small></button>)}</div><button className="secondary" onClick={applyTemplate}>套用合法模板（三幕·入场/走位/退场）</button></>}
<div className="board">{[0,1,2].map(act=><div className="act-col" key={act}><h4>第 {act+1} 幕 <small>{data?.plays?.find((p:any)=>p.id===draft.playId)?.acts?.[act]||''}</small></h4><div className="beats">{[0,1,2,3].map(beat=>{const items=board()[act][beat];return <div className="beat" key={beat}><span>拍 {beat+1}</span>{items.map(({e,i,a}:any)=>{const start=e.slot===beat;return <div className={`chip${start?'':' continuation'}${a?.id==='enter'?' enter':a?.id==='exit'?' exit':''}`} key={i} onClick={()=>removeEntry(i)} title="点击删除">{start&&<><b>{a?.name}</b><em>{e.actorIds.map((id:string)=>findActor(id)?.name).join('、')}</em></>}{!start&&<em>（续）{a?.name}</em>}</div>})}</div>})}</div></div>)}</div>
<h3>结尾改写</h3><div className="endings">{[0,1,2].map((slot)=><select key={slot} value={draft.endings[slot]} onChange={e=>setDraft((x:any)=>({...x,endings:x.endings.map((v:number,i:number)=>i===slot?Number(e.target.value):v)}))}>{(data?.plays?.find((p:any)=>p.id===draft.playId)?.endings||[]).map((x:string,i:number)=><option key={i} value={i}>{x}</option>)}</select>)}</div><button onClick={saveProduction} disabled={busy}>保存编排并检查</button>{tour.status==='READY'&&<button className="perform" onClick={perform} disabled={busy}>确认演出</button>}</div><aside className="panel"><h2>剧团状态</h2>{tour.actors.map((a:any)=><div className="actor" key={a.id}><div><b>{a.name}</b><small>{a.role} · Lv.{a.level}</small></div><meter min="0" max="100" value={a.stamina}/><small>体力 {a.stamina}</small></div>)}<button className="secondary" onClick={rest}>全员休息</button></aside></section>}
 {tour.status==='FINALE_READY'&&<section className="panel finale"><h2>终站的帷幕已经升起</h2><p>五座小镇的回声汇聚成最后一场演出。你的选择将决定剧团留下什么。</p><button onClick={finale} disabled={busy}>演出终局</button></section>}
 {perf&&<section className="panel result"><h2>演出结算</h2><div className="score">{perf.score}<small> / 100</small></div><p>{perf.feedback}</p><div className="ledger"><span>票房 <b>+{perf.income}</b></span><span>已记录为不可变演出快照</span></div></section>}
 {tour.status==='COMPLETED'&&<section className="panel"><h2>剧团档案</h2><p>本次巡演走过 {tour.visited.length} 座小镇，留下 {tour.history.length} 场演出记录。</p><button onClick={()=>{localStorage.removeItem('tour');location.reload()}}>开启新的巡演</button></section>}
 </main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
